### ISSUE TITLE
syslog littered with "failed parsing crontab for user root" errors

### ISSUE THREAD

**Issue by techie2000** [itimpi/parity.check.tuning#8]
small e.g. 
```
Mar 19 17:12:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "resume" &> /dev/null
Mar 19 17:12:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "pause" &> /dev/null
Mar 19 17:14:05 TheDeathStar emhttpd: spinning down /dev/sdd
Mar 19 17:27:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "resume" &> /dev/null
Mar 19 17:27:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "pause" &> /dev/null
Mar 19 17:42:01 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "resume" &> /dev/null
Mar 19 17:42:01 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "pause" &> /dev/null
Mar 19 17:56:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "resume" &> /dev/null
Mar 19 17:56:02 TheDeathStar crond[2274]: failed parsing crontab for user root: /usr/local/emhttp/plugins/parity.check.tuning/parity.check.tuning.php "pause" &> /dev/null
```
I have been seeing this for a while and have upgraded to the latest release and can confirm I am still seeing it in the logs.

**Comment by itimpi** [comment]
There was an error like that at one point but it was fixed a while ago  and is not something I can reproduce with the current released version..

Have you tried going into the settings and making any change and then pressing apply ad that would force a regeneration of the cron settings for the plugin.   If so and that has not fixed it can you please go into the plugins folder on the flash drive and provide the .cfg and the .cron files so I can see exactly what you have set.  The latter should have the current cron settings and the former is your current configuration file

**Comment by techie2000** [comment]
> There was an error like that at one point but it was fixed a while ago and is not something I can reproduce with the current released version..
> 
> Have you tried going into the settings and making any change and then pressing apply ad that would force a regeneration of the cron settings for the plugin.
I have just actioned this and will monitor the log for signs of change/improvement

**Comment by techie2000** [comment]
I can confirm that after "going into the settings and making any change and then pressing apply" I do not appear to be getting this error.

**Comment by itimpi** [comment]
Thanks for confirming that works.   I am going to close this issue based on that feedback
