### ISSUE TITLE
Don't understand the meaning of this term perhaps a copy/paste error ?

### ISSUE THREAD

**Issue by roquint** [itimpi/parity.check.tuning#9]
https://github.com/itimpi/parity.check.tuning/blob/384746196dbec654e09102d8c1664627cebb543a/paritychecktuning.txt#L96

**Comment by itimpi** [comment]
That text is then followed by the type of action (parity check/clear/rebuild) that is about to automatically be triggered.

**Comment by itimpi** [comment]
I have added a comment to the translation file to explain this.

If you find other entries for which a comment might help I will add them for the next person doing any translations.

**Comment by roquint** [comment]
ok i understand now, i know how to translate it now, thanks
